[versions]
androidx-test = "1.7.0"
bouncy-castle = "1.85"
dependency-license-report = "3.1.4"
dependencycheck = "13.0.0"
dokka = "2.2.0"
espresso-contrib = "3.7.0"
espresso-core = "3.7.0"
eudi-rqes-jvm = "0.8.0"
gradle-plugin = "9.2.1"
java = "17"
junit-android = "1.3.0"
kotlin = "2.3.21"
kover = "0.9.9"
kotlinx-io = "0.9.1"
kotlin-coroutines-test = "1.11.0"
ktor = "3.2.3"
mavenPublish = "0.37.0"
mockk = "1.14.11"
sonarqube = "7.4.0.8496"

[libraries]
android-junit = { module = "androidx.test.ext:junit", version.ref = "junit-android" }
bouncy-castle-pkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncy-castle" }
bouncy-castle-prov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncy-castle" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso-contrib" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso-core" }
eudi-rqes-jvm = { module = "eu.europa.ec.eudi:eudi-lib-jvm-rqes-csc-kt", version.ref = "eudi-rqes-jvm" }
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines-test" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
test-coreKtx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
dependency-license-report = { id = "com.github.jk1.dependency-license-report", version.ref = "dependency-license-report" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }